version: "3.8"
services:
  spring-boot:
    build: .
    container_name: springboot-redis-cache
    ports:
      - "8080:8080"
    depends_on:
      - my-redis
    networks:
      - cache
  my-redis:
    image: redis/redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - cache
networks:
  cache:
    driver: bridge